# Generated by Django 3.2.20 on 2024-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=55)),
                ('usertype', models.CharField(default=1, max_length=55)),
            ],
        ),
    ]
